name: simple_quran
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1                    # Untuk manajemen state (SettingsProvider)
  http: ^1.2.0                        # Untuk mengambil data API
  shared_preferences: ^2.2.2          # Untuk menyimpan bookmark & setting di HP
  google_fonts: ^6.1.0                # Untuk font Arab & Latin yang bagus
  flutter_widget_from_html: ^0.10.0   # Untuk menampilkan teks Tafsir (HTML)
  just_audio: ^0.9.36                 # Untuk memutar audio ayat
  scrollable_positioned_list: ^0.3.8  # Untuk scroll otomatis ke ayat tertentu

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#1B5E20" # (Opsional) Warna latar belakang ikon di Android (Hijau Tua)
  adaptive_icon_foreground: "assets/icon.png" # Gunakan gambar yang sama